# Generated by Django 5.0.1 on 2024-06-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_alter_salesorder_customer_alter_salesorder_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitems',
            name='subtotal',
        ),
    ]
