# Generated by Django 5.0.1 on 2024-06-05 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_remove_salesorderitems_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitems',
            name='salesorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorders', to='sales_app.salesorder'),
        ),
    ]
