# Generated by Django 5.0.1 on 2024-06-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_alter_salesorderitems_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitems',
            name='deliveredon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
