# Generated by Django 5.0.1 on 2024-06-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_salesorderitems_deliveredon'),
        ('store_app', '0003_store_isbestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.store'),
        ),
    ]
