# Generated by Django 5.0.1 on 2024-07-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0008_salesorder_totaladmincommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='vendorsubtotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vendortax',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vendortotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='vendorprice',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='vendortax',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='vendortotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
