# Generated by Django 5.0.1 on 2024-07-31 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0014_remove_account_accounttype_accounttypelist_and_more'),
        ('main_app', '0023_withdrawmoneywallet_withdrawmoneywallettransaction'),
        ('sales_app', '0009_salesorder_vendorsubtotal_salesorder_vendortax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='buyeraccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant_app.account'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoiceno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.address'),
        ),
    ]
