# Generated by Django 5.0.1 on 2024-01-15 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('streetaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('nearbyaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='customer/profile_pic')),
                ('idproof', models.CharField(blank=True, max_length=255, null=True)),
                ('idno', models.CharField(blank=True, max_length=255, null=True)),
                ('frontidproofdoc', models.FileField(blank=True, null=True, upload_to='customer/frontidproofdoc')),
                ('backidproofdoc', models.FileField(blank=True, null=True, upload_to='customer/backidproofdoc')),
                ('addressproof', models.CharField(blank=True, max_length=255, null=True)),
                ('addressno', models.CharField(blank=True, max_length=255, null=True)),
                ('frontaddressproofdoc', models.FileField(blank=True, null=True, upload_to='customer/frontaddressproofdoc')),
                ('backddressproofdoc', models.FileField(blank=True, null=True, upload_to='customer/backddressproofdoc')),
                ('pancardno', models.CharField(blank=True, max_length=10, null=True)),
                ('pancarddoc', models.FileField(blank=True, null=True, upload_to='customer/pancarddoc')),
                ('gstno', models.CharField(blank=True, max_length=50, null=True)),
                ('gstnodoc', models.FileField(blank=True, null=True, upload_to='customer/gstnodoc')),
                ('bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('bankifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('bankholder', models.CharField(blank=True, max_length=255, null=True)),
                ('bankaccountno', models.IntegerField(blank=True, null=True)),
                ('bankdoc', models.FileField(blank=True, null=True, upload_to='vendor/bankdoc')),
                ('pv', models.FloatField(default=0.0)),
                ('isactive', models.BooleanField(default=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
