# Generated by Django 5.0.1 on 2024-04-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionwallettransaction',
            name='commissionwallet',
        ),
        migrations.RemoveField(
            model_name='commissionwallettransaction',
            name='updatedby',
        ),
        migrations.DeleteModel(
            name='CommissionWallet',
        ),
        migrations.DeleteModel(
            name='CommissionWalletTransaction',
        ),
    ]
