# Generated by Django 5.0.4 on 2024-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0002_remove_commissionwallettransaction_commissionwallet_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycontactus",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companycontactus",
            name="mobile",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
