# Generated by Django 5.0.4 on 2024-05-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_alter_companycontactus_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycontactus",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                default="https://www.whatsapp.com/",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companycontactus",
            name="facbook",
            field=models.CharField(
                blank=True,
                default="https://www.facebook.com/",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companycontactus",
            name="instagram",
            field=models.CharField(
                blank=True,
                default="https://www.instagram.com/",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companycontactus",
            name="linkedin",
            field=models.CharField(
                blank=True,
                default="https://www.linkedin.com/",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companycontactus",
            name="twitter",
            field=models.CharField(
                blank=True, default="https://twitter.com/", max_length=255, null=True
            ),
        ),
    ]
