# Generated by Django 5.0.4 on 2024-05-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_companycontactus_whatsapp_and_more"),
        ("inventory_app", "0013_product_isfeatured"),
    ]

    operations = [
        migrations.AddField(
            model_name="homebanner",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory_app.productcategory",
            ),
        ),
        migrations.DeleteModel(
            name="HomeFooterBanner",
        ),
    ]
