# Generated by Django 5.0.1 on 2024-04-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closingday',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='closingtime',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='openingtime',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='storeregistrationtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
