# Generated by Django 5.0.4 on 2024-05-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "store_app",
            "0002_store_closingday_store_closingtime_store_openingtime_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="isbestseller",
            field=models.BooleanField(default=False),
        ),
    ]
