# Generated by Django 5.0.1 on 2024-08-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_store_isselectedcurrentstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='isselectedcurrentstore',
        ),
    ]
