# Generated by Django 5.0.1 on 2024-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userotp_notification_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='typeuser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
