# Generated by Django 5.0.1 on 2024-05-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='isbillingaddress',
        ),
        migrations.RemoveField(
            model_name='address',
            name='isshippingaddress',
        ),
    ]
