# Generated by Django 5.0.1 on 2024-05-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_address_isbillingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addresstype',
            field=models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Both', 'Both')], default='Both', max_length=30),
        ),
    ]
