# Generated by Django 5.0.1 on 2024-07-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_tdslogwallet_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='creditedamount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='tds',
            field=models.FloatField(default=0.0),
        ),
    ]
