# Generated by Django 5.0.1 on 2024-07-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_withdrawrequest_creditedamount_withdrawrequest_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdslogwallettransaction',
            name='transactiondate',
            field=models.DateTimeField(null=True),
        ),
    ]
