# Generated by Django 5.0.1 on 2024-07-09 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_tdslogwallettransaction_transactiondate'),
        ('sales_app', '0006_salesorder_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiondate', models.DateTimeField(null=True)),
                ('taxamount', models.FloatField(default=0.0)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('salesorderitems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_app.salesorderitems')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
