# Generated by Django 5.0.1 on 2024-07-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_taxlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transactiondetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
