# Generated by Django 5.0.1 on 2024-07-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_wallettransaction_transactiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transactionrealted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
