# Generated by Django 5.0.1 on 2024-07-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_businesslimitwallettransaction_transactiondetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='transactionid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
