# Generated by Django 5.0.1 on 2024-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isproductrejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reasonforproductrejected',
            field=models.TextField(blank=True, null=True),
        ),
    ]
