# Generated by Django 5.0.4 on 2024-04-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0002_product_isproductrejected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="admincommission",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="pv",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
