# Generated by Django 5.0.4 on 2024-05-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0004_alter_product_productname_unit_product_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unit",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="unit",
            name="symbol",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
