# Generated by Django 5.0.4 on 2024-05-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0005_rename_title_unit_name_unit_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariants",
            name="barcodeimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="inventory/productvariant/barcodeimage"
            ),
        ),
        migrations.AlterField(
            model_name="productvariants",
            name="sku",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariants",
            name="upc",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
