# Generated by Django 5.0.4 on 2024-05-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0006_productvariants_barcodeimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariants",
            name="isactive",
            field=models.BooleanField(default=False),
        ),
    ]
