# Generated by Django 5.0.4 on 2024-05-11 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0008_alter_product_isactive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariants",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory_app.product",
            ),
        ),
    ]
