# Generated by Django 5.0.4 on 2024-05-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0009_alter_productvariants_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="productvariants",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variants",
                to="inventory_app.productvariants",
            ),
        ),
    ]
