# Generated by Django 5.0.4 on 2024-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0010_alter_productimages_productvariants"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isspecialoffer",
            field=models.BooleanField(default=False),
        ),
    ]
