# Generated by Django 5.0.4 on 2024-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0011_product_isspecialoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specialofferdiscount",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="specialofferenddate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
