# Generated by Django 5.0.4 on 2024-05-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0012_product_specialofferdiscount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isfeatured",
            field=models.BooleanField(default=False),
        ),
    ]
