# Generated by Django 5.0.1 on 2024-06-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0013_product_isfeatured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admincommission',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pv',
        ),
        migrations.AddField(
            model_name='productvariants',
            name='admincommission',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='pv',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='vendorcommission',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
