# Generated by Django 5.0.1 on 2024-06-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0014_remove_product_admincommission_remove_product_pv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='vendorcommission',
        ),
    ]
