# Generated by Django 5.0.1 on 2024-06-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0015_remove_productvariants_vendorcommission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='admincommission',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='pv',
        ),
        migrations.AddField(
            model_name='product',
            name='admincommission',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pv',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
