# Generated by Django 5.0.1 on 2024-07-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0016_remove_productvariants_admincommission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='setadmincommission',
            field=models.BooleanField(default=False),
        ),
    ]
