# Generated by Django 5.0.1 on 2024-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0017_product_setadmincommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admincommission',
            field=models.FloatField(default=0.0),
        ),
    ]
