# Generated by Django 5.0.1 on 2024-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0018_alter_product_admincommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admincommission',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
