# Generated by Django 5.0.1 on 2024-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0019_alter_product_admincommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ispublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='ispublished',
            field=models.BooleanField(default=False),
        ),
    ]
