# Generated by Django 5.0.1 on 2024-07-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0014_remove_account_accounttype_accounttypelist_and_more'),
        ('main_app', '0023_withdrawmoneywallet_withdrawmoneywallettransaction'),
        ('purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesorder',
            name='selleraccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant_app.account'),
        ),
        migrations.AddField(
            model_name='purchasesorder',
            name='supplierinvoiceno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purchasesorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.address'),
        ),
    ]
