# Generated by Django 5.0.1 on 2024-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0002_purchasesorder_selleraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesorder',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
