# Generated by Django 5.0.1 on 2024-07-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_purchasesorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesorder',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
