# Generated by Django 5.0.1 on 2024-07-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0002_alter_accounttype_accounttypegroup_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vendor',
        ),
    ]
