# Generated by Django 5.0.1 on 2024-07-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0003_remove_account_customer_remove_account_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gstno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gstnodoc',
            field=models.FileField(blank=True, null=True, upload_to='store/gstnodoc'),
        ),
        migrations.AddField(
            model_name='account',
            name='nearbyaddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pancarddoc',
            field=models.FileField(blank=True, null=True, upload_to='store/pancarddoc'),
        ),
        migrations.AddField(
            model_name='account',
            name='pancardno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='streetaddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
