# Generated by Django 5.0.1 on 2024-07-24 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0004_account_city_account_country_account_gstno_and_more'),
        ('store_app', '0003_store_isbestseller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualJournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceno', models.CharField(blank=True, max_length=255, null=True)),
                ('transactiontype', models.CharField(blank=True, max_length=255, null=True)),
                ('totaldebit', models.FloatField(blank=True, default=0.0, null=True)),
                ('totalcredit', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant_app.account')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juurnaladmins', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
