# Generated by Django 5.0.1 on 2024-07-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0005_manualjournalvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualjournalvoucher',
            name='createddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
