# Generated by Django 5.0.1 on 2024-07-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0006_manualjournalvoucher_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualjournalvoucher',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='manualjournalvoucher',
            name='ismatched',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
