# Generated by Django 5.0.1 on 2024-07-24 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0007_manualjournalvoucher_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualjournalvoucher',
            name='account',
        ),
        migrations.RemoveField(
            model_name='manualjournalvoucher',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='manualjournalvoucher',
            name='ismatched',
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(blank=True, max_length=255, null=True)),
                ('totaldebit', models.FloatField(blank=True, default=0.0, null=True)),
                ('totalcredit', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('ismatched', models.BooleanField(blank=True, default=False, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant_app.account')),
                ('manualjournalvoucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant_app.manualjournalvoucher')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
