# Generated by Django 5.0.1 on 2024-07-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0008_remove_manualjournalvoucher_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualjournalvoucher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
