# Generated by Django 5.0.1 on 2024-07-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0010_alter_accountentry_manualjournalvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accounttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounttypes', to='accountant_app.accounttype'),
        ),
    ]
