# Generated by Django 5.0.1 on 2024-07-26 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0011_alter_account_accounttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiondate', models.DateTimeField()),
                ('transactiontype', models.CharField(max_length=20)),
                ('transactionamount', models.FloatField()),
                ('transactionrealted', models.CharField(blank=True, max_length=255, null=True)),
                ('transactiondetails', models.TextField(blank=True, null=True)),
                ('transactionid', models.CharField(blank=True, max_length=255, null=True)),
                ('previousamount', models.FloatField()),
                ('remainingamount', models.FloatField()),
                ('isverified', models.BooleanField(default=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountstransaction', to='accountant_app.account')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
