# Generated by Django 5.0.1 on 2024-07-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_app', '0013_accounttransaction_previousprtransactiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accounttype',
        ),
        migrations.CreateModel(
            name='AccountTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('accounttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounttypes', to='accountant_app.accounttype')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='accounttypelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounttypelists', to='accountant_app.accounttypelist'),
        ),
    ]
